name: Jest | Run Spec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Jest
        run: npm test
        env:
          PORT: 3000
          NODE_ENV: production
          THROTTLE_TTL: 60
          THROTTLE_LIMIT: 10
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_CLUSTER: ${{ secrets.DB_CLUSTER }}
          POSTMAN_COLLECTION: ${{ secrets.POSTMAN_COLLECTION }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
